services:
  springboot-app:
    image: springboot-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: upostgresser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db05
    ports:
      - "5432:5432"